### ISSUE TITLE
Another on fig up

### ISSUE THREAD

**Issue by Fohlen** [luiselizondo/docker-drupal-light#2]
The following error occurs on fig up for me:
Service "%s" doesn't have any configuration options. All top level keys in your fig.yml must map to a dictionary of configuration options.

**Comment by luiselizondo** [comment]
Did you created the data-only container? 
Did you change the image name? 
Did you create the directories /var/www and /var/log/docker?

**Comment by lmakarov** [comment]
I'm having the same issue.

> Did you created the data-only container?

No. Can you please elaborate on this?

> Did you change the image name? 

Yes.

> Did you create the directories /var/www and /var/log/docker?

I'm using "./docroot:/var/www" and removed the one for logs.

**Comment by lmakarov** [comment]
I submitted PR #3 which should fix this.
